# Generated by Django 4.2.1 on 2023-08-08 16:57

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_category_articlepost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='def-user.jpg', upload_to=core.models.default_profile_pic_path),
        ),
    ]
